pipeline {
    agent any

    environment {
        NODEJS_VERSION = '14'
    }

    stages {
        stage('Integration') {
            steps {
                // Checkout the code from your Git repository
                git 'https://github.com/saikumarvsk/Hospitality.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Change to the project directory
                    dir('Hospital-management-nodejs-master') {
                        // Set up Node.js and install project dependencies
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                     dir('Hospital-management-nodejs-master')
                    // Run your tests
                    sh 'npm test'
                }
            }
        }

        // Add more stages as needed for deployment or additional steps
    }
}
