pipeline{
  agent any
  stages{
    stage('integration')
    {
      steps{
        git 'https://github.com/saikumarvsk/Hospitality.git'
      }
    }
    stage("Sonarqube Analysis "){
            steps{
                withSonarQubeEnv('sonar') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Hospitality \
                    -Dsonar.projectKey=Hospitality '''
        }
    }
}

  }
}
